[package]
name = "wrt"
version = "0.1.0"
edition = "2021"
license.workspace = true
description = "WebAssembly Runtime Library"
build = "build.rs"

[dependencies]
# Dependencies
log = { version = "0.4", optional = true }
rayon = "1.5"
wat = "1.0"
wast = { version = "227.0.1", features = ["wasm-module", "component-model"] }

[lib]
name = "wrt"
path = "src/lib.rs"
bench = false

[dev-dependencies]
criterion = "0.5"
wat = "1.0.53"
wast = { version = "227.0.1", features = ["wasm-module", "component-model"] }
wast_proc_macro = { path = "tests/wast_proc_macro" }

[[bench]]
name = "engine_benchmarks"
harness = false

[package.metadata.cargo-udeps.ignore]
dev-dependencies = ["criterion"]

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(test)'] }

[features]
default = ["std"]
std = ["log"]
no_std = []
# Proposal features
relaxed_simd = []
gc = []
function_references = []
multi_memory = []
exception_handling = []
threads = []
extended_const = []
tail_call = []
wasm_3_0 = []
wide_arithmetic = []
custom_page_sizes = []
annotations = []
