[package]
name = "wrt"
version = "0.1.0"
edition = "2021"
license.workspace = true
description = "WebAssembly Runtime Library"

[dependencies]
# No dependencies required

[lib]
name = "wrt"
path = "src/lib.rs"

[dev-dependencies]
criterion = "0.5"

[package.metadata.cargo-udeps.ignore]
dev-dependencies = ["criterion"]

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(test)'] }

[features]
default = []
std = []
no_std = []
