[package]
name = "wrt"
version = "0.1.0"
edition = "2021"
license.workspace = true
description = "WebAssembly Runtime Library"
build = "build.rs"

[dependencies]
# Dependencies
log = { version = "0.4", optional = true }
proptest = "1.0"
rayon = "1.5"
structopt = "0.3"
wabt = "0.10"
wat = "1.0"
wast = { version = "227.0.1", features = ["wasm-module", "component-model"] }
wasm-bindgen-test = "0.3"
wasm-bindgen-test-macro = "0.3"

[lib]
name = "wrt"
path = "src/lib.rs"
bench = false

[dev-dependencies]
criterion = "0.5"
wat = "1.0.53"
wast = { version = "227.0.1", features = ["wasm-module", "component-model"] }
wasmparser = "0.116"
tempfile = "3.8"
dirs = "5.0"
wast_proc_macro = { path = "tests/wast_proc_macro" }
wasm-bindgen-test = "0.3"
wasm-bindgen-test-macro = "0.3"

[[bench]]
name = "engine_benchmarks"
harness = false

[package.metadata.cargo-udeps.ignore]
dev-dependencies = ["criterion"]

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(test)'] }

[features]
default = ["std"]
std = ["log"]
no_std = []
