[package]
name = "example"
version = "0.1.0"
edition = "2021"
license.workspace = true
description = "Example WebAssembly Module using WASI logging"

[lib]
crate-type = ["cdylib"]

# Set default target to wasm32-wasip2
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
# Use wit-bindgen from workspace with realloc feature
wit-bindgen = { workspace = true, features = ["realloc"] }

# Add build-dependencies for the build script
[build-dependencies]
anyhow = { workspace = true }

# Add component metadata
[package.metadata.component.target]
path = "../wit/deps" # Base path for dependencies
world = "hello-world" # World defined in wit/example.wit

# Define dependencies 
[package.metadata.component.target.dependencies]
"wasi:logging" = { version = "0.2.0-preview2" } # Use the preview2 version
"wasi:cli" = { version = "0.2.0-preview2" }
"wasi:io" = { version = "0.2.0-preview2" }
"wasi:clocks" = { version = "0.2.0-preview2" }

# REMOVED: Redundant dependency definition
# [package.metadata.component.dependencies]
# "wasi:logging" = { path = "../wit/wasi/logging" }


