[package]
name = "example"
version = "0.1.0"
edition = "2021"
license.workspace = true
description = "Example WebAssembly Module using WASI logging"

[lib]
crate-type = ["cdylib"]

# Set default target to wasm32-wasip2
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
# Use wit-bindgen from workspace with realloc feature
wit-bindgen = { workspace = true, features = ["realloc"] }

# Add build-dependencies for the build script
[build-dependencies]
anyhow = { workspace = true }

