# WRT Allowed Unsafe Code Configuration
# This file documents approved unsafe code blocks that are necessary for ASIL compliance
# Each entry must include justification and be re-evaluated when code changes

# Format:
# [[allowed]]
# file = "relative/path/to/file.rs"
# line = 123  # Optional: specific line number
# function = "function_name"  # Optional: function name for context
# reason = "Brief explanation of why unsafe is required"
# asil_justification = "ASIL-specific safety justification"

# Waker API - Required by Rust standard library
[[allowed]]
file = "wrt-component/src/async_/fuel_aware_waker.rs"
line = 320
function = "create_fuel_aware_waker"
reason = "Rust's Waker API requires unsafe for Waker::from_raw"
asil_justification = "ASIL-D compliant: Valid heap-allocated WakerData pointer with proper cleanup via waker_drop"

[[allowed]]
file = "wrt-component/src/async_/fuel_aware_waker.rs"
line = 338
function = "create_fuel_aware_waker"
reason = "Rust's Waker API requires unsafe for Waker::from_raw"
asil_justification = "ASIL-D compliant: Noop waker with null pointer data, all vtable functions are no-ops"

[[allowed]]
file = "wrt-component/src/async_/fuel_async_executor.rs"
line = 2911
function = "create_noop_waker"
reason = "Rust's Waker API requires unsafe for Waker::from_raw"
asil_justification = "ASIL-D compliant: Noop waker with null pointer data, no memory access or dereferencing"

# Waker vtable functions - Required for non-ASIL-D builds
[[allowed]]
file = "wrt-component/src/async_/fuel_aware_waker.rs"
line = 217
function = "waker_clone"
reason = "Waker vtable function signature requires unsafe"
asil_justification = "Only used in non-ASIL-D builds with proper feature gates"

[[allowed]]
file = "wrt-component/src/async_/fuel_aware_waker.rs"
line = 227
function = "waker_wake"
reason = "Waker vtable function signature requires unsafe"
asil_justification = "Only used in non-ASIL-D builds with proper feature gates"

[[allowed]]
file = "wrt-component/src/async_/fuel_aware_waker.rs"
line = 233
function = "waker_wake_by_ref"
reason = "Waker vtable function signature requires unsafe"
asil_justification = "Only used in non-ASIL-D builds with proper feature gates"

[[allowed]]
file = "wrt-component/src/async_/fuel_aware_waker.rs"
line = 239
function = "waker_drop"
reason = "Waker vtable function signature requires unsafe"
asil_justification = "Only used in non-ASIL-D builds with proper feature gates"

# Memory profiler - No-std environments
[[allowed]]
file = "wrt-debug/src/memory_profiling.rs"
line = 881
function = "with_profiler"
reason = "No-std environment requires raw pointer access for static memory profiler"
asil_justification = "ASIL-D compliant: Pointer from Box::leak with 'static lifetime, single initialization guarantee"

# cargo-wrt CLI validation - Not safety critical
[[allowed]]
file = "cargo-wrt/src/main.rs"
function = "validate_cli"
reason = "CLI validation macros for compile-time checks"
asil_justification = "CLI tool validation only - not part of runtime safety-critical code"

# Emergency fallback code - No-std environments only
[[allowed]]
file = "wrt-component/src/threading/task_cancellation.rs"
line = 696
function = "new"
reason = "Emergency fallback for CancellationTokenInner in no_std environment"
asil_justification = "ASIL-A: Only used when std feature disabled and proper initialization fails. Will be replaced with safe alternative."

[[allowed]]
file = "wrt-component/src/threading/task_cancellation.rs"
line = 712
function = "default"
reason = "Emergency fallback for SubtaskManager in no_std environment"
asil_justification = "ASIL-A: Only used when std feature disabled and proper initialization fails. Will be replaced with safe alternative."

[[allowed]]
file = "wrt-component/src/threading/task_cancellation.rs"
line = 716
function = "default"
reason = "Emergency fallback for completion handlers in no_std environment"
asil_justification = "ASIL-A: Only used when std feature disabled and proper initialization fails. Will be replaced with safe alternative."

# SIMD operations - Math library
[[allowed]]
file = "wrt-math/src/safety.rs"
line = 615
function = "simd_operation"
reason = "SIMD operations marked as requiring unsafe code path"
asil_justification = "ASIL-A: Error message indicating unsafe code requirement, actual unsafe code gated behind higher ASIL levels"

[[allowed]]
file = "wrt-math/src/safety.rs"
line = 631
function = "simd_operation"
reason = "SIMD operations marked as requiring unsafe code path"
asil_justification = "ASIL-A: Error message indicating unsafe code requirement, actual unsafe code gated behind higher ASIL levels"

# CFI integration - Control flow integrity
[[allowed]]
file = "wrt/src/cfi_integration.rs"
line = 415
function = "validate_cfi"
reason = "CFI validation requires unsafe pointer dereferencing for stack validation"
asil_justification = "ASIL-A: CFI stack validation with bounds checking, controlled pointer access"

# Instruction execution - Core runtime
[[allowed]]
file = "wrt-instructions/src/execution.rs"
line = 92
function = "execute_instruction"
reason = "Instruction execution requires unsafe memory access for performance"
asil_justification = "ASIL-A: Bounds-checked memory access with capability validation"

# Test code - Not production
[[allowed]]
file = "wrt/tests/wasm_testsuite.rs"
function = "test_v128_values"
reason = "Test code for SIMD value verification"
asil_justification = "Test code only - not included in production builds"