[workspace]
members = [
    "wrt",
    "wrtd",
    "xtask",
    "example",
    "wrt-sync",
    "wrt-error",
    "wrt-format",
    "wrt-types",
    "wrt-decoder",
    "wrt-component",
    "wrt-host",
    "wrt-logging",
    "wrt-runtime",
    "wrt-instructions",
    "wrt-intercept", "test-control-instructions",
    "wrt-verification-tool",
    "wrt-test-registry",
]
resolver = "2"  # Use edition 2021 resolver

[workspace.package]
version = "0.2.0"
edition = "2021"
rust-version = "1.86.0"
license = "MIT"

[workspace.dependencies]
anyhow = "1.0"
wit-bindgen = "0.41.0"
dagger-sdk = { version = "0.18.6", features = ["codegen"] }

# Internal crate versions
wrt = { path = "wrt", version = "0.2.0" }
wrt-error = { path = "wrt-error", version = "0.2.0" }
wrt-sync = { path = "wrt-sync", version = "0.2.0" }
wrt-format = { path = "wrt-format", version = "0.2.0" }
wrt-types = { path = "wrt-types", version = "0.2.0" }
wrt-decoder = { path = "wrt-decoder", version = "0.2.0" }
wrt-runtime = { path = "wrt-runtime", version = "0.2.0" }
wrt-logging = { path = "wrt-logging", version = "0.2.0" }
wrt-instructions = { path = "wrt-instructions", version = "0.2.0" }
wrt-component = { path = "wrt-component", version = "0.2.0" }
wrt-host = { path = "wrt-host", version = "0.2.0" }
wrt-intercept = { path = "wrt-intercept", version = "0.2.0" }
wrt-test-registry = { path = "wrt-test-registry", version = "0.2.0" }

[workspace.lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(test)'] }
unused_imports = "allow"
unused_variables = "allow"
unused_mut = "allow"
unused_macros = "allow"

# Workspace-level profiles inherit by members unless overridden.
# Setting panic=abort globally for safety.
[workspace.profile.dev]
panic = "abort"
# Inherits other settings from Cargo's defaults

[workspace.profile.release]
panic = "abort"
strip = true  # Reduce binary size
lto = true    # Link-Time Optimization
codegen-units = 1 # Maximize optimization opportunities

[workspace.profile.test]
panic = "abort"
# Inherits other settings from Cargo's defaults (e.g., debug assertions enabled)

[workspace.profile.bench]
panic = "abort"
# Inherits from release profile by default, but we ensure panic=abort here too.
