[workspace]
members = [
    "wrt",
    "wrtd",
    "example"
]
resolver = "2"  # Use edition 2021 resolver

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
wit-bindgen = "0.12.0"

[workspace.lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(test)'] }
