[workspace]
members = [
    "wrt",
    "wrtd",
    "xtask",
    "example",
    "wrt-sync",
    "wrt-error",
    "wrt-format",
    "wrt-types",
    "wrt-decoder",
    "wrt-component",
    "wrt-math",
    "wrt-host",
    "wrt-logging",
    "wrt-runtime",
    "wrt-instructions",
    "wrt-intercept", "test-control-instructions",
    "wrt-verification-tool",
    "wrt-test-registry",
    "wrt-platform",
]
resolver = "2"  # Use edition 2021 resolver

[workspace.package]
authors = ["The WRT Project Developers"]
edition = "2021"
license = "MIT"
repository = "placeholder/repo.git" # TODO: Replace with actual repo URL
version = "0.2.0" # Updated to 0.2.0 for consistency

[workspace.dependencies]
anyhow = "1.0"
wit-bindgen = "0.41.0"
dagger-sdk = { version = "0.18.6", features = ["codegen"] }

# Internal crate versions
wrt = { path = "wrt", workspace = true }
wrt-error = { path = "wrt-error", workspace = true }
wrt-sync = { path = "wrt-sync", workspace = true }
wrt-format = { path = "wrt-format", workspace = true }
wrt-types = { path = "wrt-types", workspace = true }
wrt-decoder = { path = "wrt-decoder", workspace = true }
wrt-runtime = { path = "wrt-runtime", workspace = true }
wrt-logging = { path = "wrt-logging", workspace = true }
wrt-instructions = { path = "wrt-instructions", workspace = true }
wrt-component = { path = "wrt-component", workspace = true }
wrt-host = { path = "wrt-host", workspace = true }
wrt-intercept = { path = "wrt-intercept", workspace = true }
wrt-test-registry = { path = "wrt-test-registry", workspace = true }
wrt-math = { path = "wrt-math", workspace = true }
wrt-platform = { path = "wrt-platform", workspace = true }
wrt-verification-tool = { path = "wrt-verification-tool", workspace = true }

[workspace.lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(test)'] }
unused_imports = "allow"
unused_variables = "allow"
unused_mut = "allow"
unused_macros = "allow"

# Workspace-level profiles inherit by members unless overridden.
# Setting panic=abort globally for safety.
[workspace.profile.dev]
panic = "abort"
# Inherits other settings from Cargo's defaults

[workspace.profile.release]
panic = "abort"
strip = true  # Reduce binary size
lto = true    # Link-Time Optimization
codegen-units = 1 # Maximize optimization opportunities

[workspace.profile.test]
panic = "abort"
# Inherits other settings from Cargo's defaults (e.g., debug assertions enabled)

[workspace.profile.bench]
panic = "abort"
# Inherits from release profile by default, but we ensure panic=abort here too.
