[workspace]
members = [
    "wrt",
    "wrtd",
    "xtask",
    "example",
    "wrt-sync",
    "wrt-error",
    "wrt-format",
    "wrt-types",
    "wrt-decoder",
    "wrt-component",
    "wrt-host",
    "wrt-logging",
    "wrt-runtime",
    "wrt-instructions",
    "wrt-intercept",
]
resolver = "2"  # Use edition 2021 resolver

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.86.0"
license = "MIT"

[workspace.dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
wit-bindgen = "0.41.0"
wrt-types = { path = "./wrt-types", version = "0.1.0" }
wrt-format = { path = "./wrt-format", version = "0.1.0" }

[workspace.lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(test)'] }
unused_imports = "allow"
unused_variables = "allow"
unused_mut = "allow"
unused_macros = "allow"
