[workspace]
members = [
    "wrt",
    "wrtd",
    "xtask",
    "example",
    "wrt-sync",
    "wrt-error",
    "wrt-format",
    "wrt-types",
    "wrt-decoder",
    "wrt-component",
    "wrt-host",
    "wrt-logging",
    "wrt-runtime",
    "wrt-instructions",
    "wrt-intercept", "test-control-instructions",
    "wrt-verification-tool",
]
resolver = "2"  # Use edition 2021 resolver

[workspace.package]
version = "0.2.0"
edition = "2021"
rust-version = "1.86.0"
license = "MIT"

[workspace.dependencies]
anyhow = "1.0"
wit-bindgen = "0.41.0"

[workspace.lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(test)'] }
unused_imports = "allow"
unused_variables = "allow"
unused_mut = "allow"
unused_macros = "allow"
