[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MPL-2.0",
    "Unlicense",
]
# unlicensed = "deny" # Behavior is now deny by default with version = 2
# copyleft = "warn"   # Behavior is now deny by default unless allowed, with version = 2
confidence-threshold = 0.92

[bans]
multiple-versions = "warn"
wildcards = "allow" # Workspaces often use this
highlight = "all"

# Example: Deny a specific problematic crate version
# [[bans.deny]]
# name = "some-crate"
# version = "=0.1.0"
# reason = "Known security issue in this specific version"

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
# vulnerability = "deny" # Behavior is now deny by default with version = 2
# unmaintained = "warn" # Behavior is now deny by default with version = 2 (but see note below)
# unsound = "deny"       # Behavior is now deny by default with version = 2
yanked = "warn"
# notice = "warn"         # Behavior is now deny by default with version = 2
ignore = []
# severity-threshold = "medium" # Removed with version = 2

# Note: cargo-deny 0.18.2 re-added `advisories.unmaintained` as an option.
# If the project uses >= 0.18.2 and needs to warn for unmaintained instead of deny,
# this line can be uncommented: 
# unmaintained = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
allow-registry = ["https://crates.io"] 