[meta]
project = "WRT WebAssembly Runtime"
version = "0.2.0"
safety_standard = "ISO26262"

[[requirement]]
id = "REQ_MEM_001"
title = "Memory Bounds Checking"
description = "All memory operations must be bounds-checked to prevent buffer overflows"
type = "Memory"
asil_level = "AsilC"
implementations = ["wrt-foundation/src/safe_memory.rs"]
tests = ["wrt-foundation/tests/memory_tests_moved.rs"]
documentation = ["docs/architecture/memory_model.rst"]

[[requirement]]
id = "REQ_SAFETY_001"
title = "ASIL Context Maintenance"
description = "Runtime must maintain safety context with ASIL level tracking"
type = "Safety"
asil_level = "AsilD"
implementations = ["wrt-foundation/src/safety_system.rs"]
tests = ["wrt-foundation/tests/"]
documentation = ["docs/architecture/safety.rst"]

[[requirement]]
id = "REQ_COMP_001"
title = "Component Isolation"
description = "Components must be isolated from each other with proper resource boundaries"
type = "Component"
asil_level = "AsilC"
implementations = ["wrt-component/src/bounded_resource_management.rs"]
tests = ["wrt-component/tests/resource_management_tests.rs"]
documentation = ["docs/architecture/component_model.rst"]

[[requirement]]
id = "REQ_ASYNC_001"
title = "Async Task Management"
description = "Async operations must be properly managed with task cancellation and resource cleanup"
type = "Runtime"
asil_level = "AsilB"
implementations = ["wrt-component/src/threading/task_manager.rs", "wrt-component/src/async_/async_canonical.rs"]
tests = ["wrt-component/tests/async_features_integration_test.rs"]
documentation = ["docs/architecture/async_threading.rst"]

[[requirement]]
id = "REQ_PARSE_001"
title = "Bounded WIT Parsing"
description = "WIT parsing must respect memory limits and prevent unbounded allocation"
type = "Parse"
asil_level = "AsilC"
implementations = ["wrt-format/src/bounded_wit_parser.rs"]
tests = ["wrt-format/tests/parser_test_reference.rs"]
documentation = ["docs/architecture/intercept_system.rst"]

[[requirement]]
id = "REQ_ERROR_001"
title = "Structured Error Handling"
description = "All errors must be categorized and traceable with proper context"
type = "System"
asil_level = "AsilB"
implementations = ["wrt-error/src/errors.rs", "wrt-error/src/codes.rs"]
tests = ["wrt-error/tests/error_conversion_test.rs"]
documentation = ["docs/architecture/logging.rst"]

[[requirement]]
id = "REQ_ADVANCED_THREADING_001"
title = "Advanced Threading Support"
description = "Advanced threading capabilities including task management, spawning, and synchronization"
type = "Runtime"
asil_level = "AsilB"
implementations = ["wrt-component/src/threading/advanced_threading_builtins.rs", "wrt-component/src/threading/thread_builtins.rs"]
tests = ["wrt-component/tests/"]
documentation = ["docs/source/requirements.rst"]