[package]
name = "wrt-foundation-fuzz"
version = "0.2.0"
publish = false
edition = "2021"
authors = ["The WRT Project Developers"]
license = "MIT"
description = "Fuzz testing for WRT Foundation components"

[package.metadata]
cargo-fuzz = true

[workspace]
# This is a standalone fuzz testing package

[lib]
name = "wrt_foundation_fuzz"
path = "mod.rs"

[dependencies]
# Fuzzing dependencies
libfuzzer-sys = "0.4"
arbitrary = { version = "1", features = ["derive"] }

# WRT dependencies  
wrt-foundation = { path = "../..", features = ["std"] }
wrt-runtime = { path = "../../../wrt-runtime", features = ["std"] }
wrt = { path = "../../../wrt", features = ["std"] }

# Standard library for std-compatible tests
[features]
default = ["std"]
std = []

# Fuzz targets
[[bin]]
name = "fuzz_bounded_vec"
path = "fuzz_targets/fuzz_bounded_vec.rs"
test = false
doc = false

[[bin]]
name = "fuzz_bounded_stack"
path = "fuzz_targets/fuzz_bounded_stack.rs"
test = false
doc = false

[[bin]]
name = "fuzz_memory_adapter"
path = "fuzz_targets/fuzz_memory_adapter.rs"
test = false
doc = false

[[bin]]
name = "fuzz_safe_slice"
path = "fuzz_targets/fuzz_safe_slice.rs"
test = false
doc = false