[package]
name = "wrt-intercept"
version = "0.2.0"
edition = "2021"
description = "Host interception for WebAssembly Runtime (WRT)"
license = "MIT OR Apache-2.0"
repository = "https://github.com/avrabe/wrt"
documentation = "https://docs.rs/wrt-intercept"
keywords = ["wasm", "webassembly", "runtime", "interception"]
categories = ["wasm", "no-std"]

[dependencies]
wrt-error = { path = "../wrt-error", version = "0.2.0" }
wrt-types = { path = "../wrt-types", version = "0.2.0" }
wrt-format = { path = "../wrt-format", version = "0.2.0" }

# Optional dependencies
log = { version = "0.4", optional = true }
# For formal verification when 'kani' feature is enabled
kani-verifier = { version = "0.61.0", optional = true }

[dev-dependencies]
chrono = "0.4"  # For examples
pretty_assertions = "1.4.0"

[features]
default = ["std"]
std = ["wrt-error/std", "wrt-types/std", "wrt-format/std", "log"]
no_std = ["wrt-error/no_std", "wrt-types/no_std", "wrt-format/no_std"]
kani = ["dep:kani-verifier"]

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(test)', 'cfg(kani)', 'cfg(coverage)', 'cfg(doc)'] }
unused_imports = "allow"
unused_variables = "allow"
unused_mut = "allow"
unused_macros = "allow"

# Configuration for Kani verification
# This will only be used when running `cargo kani`
[package.metadata.kani]
enabled-checks = ["assertion", "overflow"]
default-unwind = 2 