[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = []
wrt-integration = ["wrt"]

[dependencies]
xshell = "0.2.5"

# Additions for symbols task
anyhow = "1.0"
clap = { version = "4.5", features = ["derive", "env"] }
rustc-demangle = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tera = "1"

walkdir = "2"
fs_extra = "1.3" # For cross-platform rm -rf and mkdir -p equivalent
wasm-tools = { version = "1.228.0" }
wat = "1.228.0"
wrt = { path = "../wrt", optional = true }

# For documentation HTTP server
tiny_http = "0.12"

# Check for the latest compatible version 