[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
walkdir = "2"
fs_extra = "1.3" # For cross-platform rm -rf and mkdir -p equivalent
wasm-tools = { version = "1.228.0" }
wat = "1.228.0"
wrt = { path = "../wrt" }

# Check for the latest compatible version 