[package]
name = "xtask"
version.workspace = true
edition.workspace = true
publish = false
repository = "https://github.com/avrabe/wrt"

[features]
default = []
wrt-integration = ["wrt"]

[dependencies]
xshell = "0.2.5"

# Additions for symbols task
anyhow = "1.0.75"
clap = { version = "4.4.3", features = ["derive"] }
rustc-demangle = "0.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0"
tera = "1"
colored = "2.0.4"

walkdir = "2"
fs_extra = "1.3" # For cross-platform rm -rf and mkdir -p equivalent
wasm-tools = { version = "1.229.0" }
wat = "1.229.0"
wrt = { path = "../wrt", optional = true }

# For documentation HTTP server
tiny_http = "0.12"

# Check for the latest compatible version
toml = "0.7.6"
syn = { version = "2.0.34", features = ["parsing", "full", "extra-traits"] }
regex = "1.9.5"
chrono = "0.4.24" 