[package]
name = "wrt-integration-tests"
version = "0.1.0"
edition = "2021"
description = "Integration tests for WRT components"

[lib]
name = "wrt_integration_tests"
path = "lib.rs"

[dependencies]
# Use workspace dependencies
wrt = { workspace = true }
wrt-component = { workspace = true }
wrt-decoder = { workspace = true }
wrt-format = { workspace = true }
wrt-foundation = { workspace = true }
wrt-host = { workspace = true }
wrt-instructions = { workspace = true }
wrt-platform = { workspace = true }
wrt-runtime = { workspace = true }
wrt-sync = { workspace = true }
wrt-test-registry = { workspace = true }

# Testing utilities
criterion = { workspace = true }
proptest = { workspace = true }
tempfile = { workspace = true }
wasmparser = { workspace = true }
wat = { workspace = true }

[[test]]
name = "component_model_tests"
path = "component_model/mod.rs"

[[test]]
name = "runtime_tests"
path = "runtime/mod.rs"

[[test]]
name = "platform_tests"
path = "platform/mod.rs"

[[test]]
name = "no_std_tests"
path = "no_std/mod.rs"

[[test]]
name = "security_tests"
path = "security/mod.rs"

