[package]
name = "wrt-host"
version = "0.2.0"
edition = "2021"
description = "Host function infrastructure for the WebAssembly Runtime (WRT)"
license = "MIT"
repository = "https://github.com/avrabe/wrt"
documentation = "https://docs.rs/wrt-host"
keywords = ["wasm", "webassembly", "runtime", "host", "component-model"]
categories = ["wasm", "no-std"]

[dependencies]
wrt-error = { path = "../wrt-error", version = "0.2.0" }
wrt-types = { path = "../wrt-types", version = "0.2.0" }
wrt-intercept = { path = "../wrt-intercept", version = "0.2.0" }

# Std dependencies
log = { version = "0.4", optional = true }
parking_lot = { version = "0.12", optional = true }

# Feature gates
[features]
default = ["std"]
std = ["log", "parking_lot", "wrt-error/std", "wrt-types/std", "wrt-intercept/std"]
no_std = ["wrt-error/no_std", "wrt-types/no_std", "wrt-intercept/no_std"]
kani = ["wrt-intercept/kani"]

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(test)', 'cfg(kani)', 'cfg(coverage)', 'cfg(doc)'] }
unused_imports = "allow"
unused_variables = "allow"
unused_mut = "allow"
unused_macros = "allow" 