[package]
name = "wrt-decoder"
version = "0.2.0"
edition = "2021"
description = "WebAssembly module decoder for wrt runtime"
license = "MIT"
repository = "https://github.com/avrabe/wrt"

[dependencies]
# Error handling
wrt-error = { path = "../wrt-error", version = "0.2.0" }
# Format handling
wrt-format = { path = "../wrt-format", version = "0.2.0" }
# Shared type definitions
wrt-types = { path = "../wrt-types", version = "0.2.0" }
# Core dependencies
log = { version = "0.4", optional = true }
# WAT parsing (for testing)
wat = { version = "1.229.0", optional = true }

[dev-dependencies]
criterion = "0.5"
tempfile = "3.8"
proptest = "1.4"
hex = "0.4"
wat = "1.229.0"

[features]
default = [
    "minimal",
    "std",
    "component-model-core",
    "component-model-values",
    "component-model-fixed-lists",
    "component-model-namespaces"
]
minimal = ["dep:log", "wrt-types/std"]
std = ["minimal", "wrt-types/std"]
no_std = ["wrt-types/no_std"]
optimize = ["wrt-types/optimize"]
safety = ["wrt-types/safety"]
wat = ["dep:wat", "std"]

# Component Model features
component-model-core = ["wrt-format/component-model-core"]
component-model-values = ["wrt-format/component-model-values"]
component-model-resources = ["wrt-format/component-model-resources"]
component-model-fixed-lists = ["wrt-format/component-model-fixed-lists"]
component-model-namespaces = ["wrt-format/component-model-namespaces"]
component-model-all = [
    "component-model-core",
    "component-model-values",
    "component-model-resources",
    "component-model-fixed-lists",
    "component-model-namespaces"
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"] 