[package]
name = "wrtd"
version = "0.1.0"
edition = "2021"
license = { workspace = true }
description = "WebAssembly Runtime Daemon"

[dependencies]
wrt = { path = "../wrt", optional = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
anyhow = { workspace = true }

