[package]
name = "wrtd"
version = "0.1.0"
edition = "2021"
license = { workspace = true }
description = "WebAssembly Runtime Daemon"

[dependencies]
wrt = { path = "../wrt", features = ["std"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
anyhow = { workspace = true }
clap = { version = "4.5.32", features = ["derive"] }

