[package]
name = "wrtd"
version.workspace = true
edition.workspace = true
license = { workspace = true }
description = "WebAssembly Runtime Daemon (std-only host implementation)"
repository = "https://github.com/avrabe/wrt"

[dependencies]
wrt = { workspace = true, features = ["std"] }
wrt-component = { workspace = true, features = ["std"] }
wrt-intercept = { workspace = true, features = ["std"] }
# Standard library dependencies
clap = { version = "4.5.37", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version= "0.3", features = ["json"] }
anyhow = { workspace = true }
once_cell = "1.18"

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(test)'] }

