[package]
name = "wrtd"
version = "0.2.0"
edition = "2021"
license = { workspace = true }
description = "WebAssembly Runtime Daemon (std-only host implementation)"

[dependencies]
wrt = { path = "../wrt", version = "0.2.0", features = ["std"] }
wrt-component = { path = "../wrt-component", version = "0.2.0", features = ["std"] }
wrt-intercept = { path = "../wrt-intercept", version = "0.2.0", features = ["std"] }
# Standard library dependencies
clap = { version = "4.5.37", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version= "0.3", features = ["json"] }
anyhow = "1.0"
once_cell = "1.18"

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(test)'] }

