[package]
name = "wrt-component"
version = "0.1.0"
edition = "2021"
description = "WebAssembly Component Model support for WRT"
license = "MIT OR Apache-2.0"
repository = "https://github.com/avrabe/wrt"
documentation = "https://docs.rs/wrt-component"
keywords = ["wasm", "webassembly", "runtime", "component-model"]
categories = ["wasm", "no-std"]

[dependencies]
wrt-error = { path = "../wrt-error", version = "0.1.0" }
wrt-format = { path = "../wrt-format", version = "0.1.0" }
wrt-host = { path = "../wrt-host", version = "0.1.0" }
wrt-types = { path = "../wrt-types", version = "0.1.0" }
wrt-intercept = { path = "../wrt-intercept", version = "0.1.0" }

# Optional dependencies
log = { version = "0.4", optional = true }
chrono = { version = "0.4", optional = true }

[dev-dependencies]
ratatui = "0.29.0"
crossterm = "0.27.0"
strum = { version = "0.26", features = ["derive"] }
tui-nodes = "0.8.0"

[features]
default = ["std"]
std = [
    "wrt-error/std",
    "wrt-format/std",
    "wrt-host/std",
    "wrt-types/std",
    "wrt-intercept/std",
    "chrono",
    "log",
]
no_std = [
    "wrt-error/no_std",
    "wrt-format/no_std",
    "wrt-host/no_std",
    "wrt-types/no_std",
    "wrt-intercept/no_std"
]
kani = ["wrt-host/kani", "wrt-intercept/kani"]

# Component Model features
component-model-core = ["wrt-format/component-model-core"]
component-model-values = ["wrt-format/component-model-values"]
component-model-resources = ["wrt-format/component-model-resources"]
component-model-all = [
    "component-model-core",
    "component-model-values",
    "component-model-resources"
]

[[example]]
name = "component_info_simple"
path = "examples/component_info_simple.rs"
required-features = ["std"]

[[example]]
name = "component_graph_view"
path = "examples/component_graph_view.rs"
required-features = ["std"]

[[example]]
name = "interceptor_example"
path = "examples/interceptor_example.rs"
required-features = ["std"]

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(test)'] }
unused_imports = "allow"
unused_variables = "allow"
unused_mut = "allow"
unused_macros = "allow" 
