[package]
name = "wrt-component"
version.workspace = true
edition.workspace = true
description = "WebAssembly Component Model support for WRT"
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/wrt-component"
keywords = ["wasm", "webassembly", "runtime", "component-model"]
categories = ["wasm", "no-std"]

[dependencies]
wrt-error = { path = "../wrt-error", workspace = true }
wrt-format = { path = "../wrt-format", workspace = true }
wrt-host = { path = "../wrt-host", workspace = true }
wrt-types = { path = "../wrt-types", workspace = true }
wrt-intercept = { path = "../wrt-intercept", workspace = true }
wrt-decoder = { path = "../wrt-decoder", workspace = true }
wrt-runtime = { path = "../wrt-runtime", workspace = true }

# No-std support
alloc = { version = "1.0.0", optional = true, package = "rustc-std-workspace-alloc" }

# Optional dependencies
log = { version = "0.4", optional = true }
futures = { version = "0.3", optional = true }

[dev-dependencies]
ratatui = "0.29.0"
crossterm = "0.27.0"
strum = { version = "0.26", features = ["derive"] }
tui-nodes = "0.8.0"

[features]
default = ["std"]
std = [
    "wrt-error/std",
    "wrt-format/std",
    "wrt-host/std",
    "wrt-types/std",
    "wrt-intercept/std",
    "wrt-decoder/std",
    "wrt-runtime/std",
    "log",
]
no_std = [
    "wrt-error/no_std",
    "wrt-format/no_std",
    "wrt-host/no_std",
    "wrt-types/no_std",
    "wrt-intercept/no_std",
    "wrt-decoder/no_std",
    "wrt-runtime/no_std",
    "alloc"
]
alloc = ["wrt-error/alloc", "wrt-format/alloc", "wrt-host/alloc", "wrt-types/alloc", "wrt-intercept/alloc", "wrt-decoder/alloc", "wrt-runtime/alloc", "dep:alloc"]
kani = ["wrt-host/kani", "wrt-intercept/kani"]

# Performance and safety features
optimize = ["wrt-error/optimize", "wrt-format/optimize", "wrt-host/optimize", "wrt-types/optimize", "wrt-intercept/optimize", "wrt-decoder/optimize", "wrt-runtime/optimize"]
safety = ["wrt-error/safety", "wrt-format/safety", "wrt-host/safety", "wrt-types/safety", "wrt-intercept/safety", "wrt-decoder/safety", "wrt-runtime/safety", "alloc"]

# Component Model features
component-model-core = ["wrt-format/component-model-core"]
component-model-values = ["wrt-format/component-model-values"]
component-model-resources = ["wrt-format/component-model-resources"]
component-model-async = ["wrt-types/component-model-async", "futures"]
component-model-error-context = ["wrt-types/component-model-error-context"]
component-model-threading = ["wrt-types/component-model-threading"]
component-model-all = [
    "component-model-core",
    "component-model-values",
    "component-model-resources",
    "component-model-async",
    "component-model-error-context",
    "component-model-threading"
]

[[example]]
name = "component_info_simple"
path = "examples/component_info_simple.rs"
required-features = ["std"]

[[example]]
name = "component_graph_view"
path = "examples/component_graph_view.rs"
required-features = ["std"]

[[example]]
name = "interceptor_example"
path = "examples/interceptor_example.rs"
required-features = ["std"]

[profile.release]
panic = "abort"

[profile.test]
panic = "abort"

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(test)'] }
# Rule 1
pointer_cast = "deny"
# Rule 9
missing_docs = "deny"
unsafe_code = "forbid"

[lints.clippy]
# Rule 1: Language subset
inline_asm_x86_att_syntax = "warn"
transmute_ptr_to_ref = "deny"
type_id = "deny"
dyn_trait = "warn"
float_arithmetic = "warn"
# Rule 2: Unsafe usage
ptr_offset_with_cast = "warn"
# Rule 3: Error handling & panics
unwrap_used = "warn"
panic = "warn" # Also covers Rule 4
result_unit_err = "warn"
let_underscore_drop = "warn"
must_use_candidate = "warn"
must_use_unit = "warn"
# Rule 4: Control-flow soundness
match_wildcard_for_single_variants = "warn"
never_loop = "warn"
unreachable = "warn" # Also related to Rule 4
# Rule 5: Memory & concurrency safety
static_mut_reference = "deny"
arc_mutate = "deny"
# Rule 8: Static analysis gates (CI)
pedantic = "warn"
# Rule 9: Documentation
debug_assert_with_mut_call = "warn" 
