[package]
name = "wrt-component"
version.workspace = true
edition.workspace = true
description = "WebAssembly Component Model support for WRT"
license.workspace = true
repository = "https://github.com/avrabe/wrt"
documentation = "https://docs.rs/wrt-component"
keywords = ["wasm", "webassembly", "runtime", "component-model"]
categories = ["wasm", "no-std"]

[dependencies]
wrt-error = { path = "../wrt-error", version = "0.2.0" }
wrt-format = { path = "../wrt-format", version = "0.2.0" }
wrt-host = { path = "../wrt-host", version = "0.2.0" }
wrt-types = { path = "../wrt-types", version = "0.2.0" }
wrt-intercept = { path = "../wrt-intercept", version = "0.2.0" }
wrt-decoder = { path = "../wrt-decoder", version = "0.2.0" }

# No-std support
alloc = { version = "1.0.0", optional = true, package = "rustc-std-workspace-alloc" }

# Optional dependencies
log = { version = "0.4", optional = true }
futures = { version = "0.3", optional = true }

[dev-dependencies]
ratatui = "0.29.0"
crossterm = "0.28.1"
strum = { version = "0.26", features = ["derive"] }
tui-nodes = "0.8.0"

[features]
default = ["std"]
std = [
    "wrt-error/std",
    "wrt-format/std",
    "wrt-host/std",
    "wrt-types/std",
    "wrt-intercept/std",
    "wrt-decoder/std",
    "log",
]
no_std = [
    "wrt-error/no_std",
    "wrt-format/no_std",
    "wrt-host/no_std",
    "wrt-types/no_std",
    "wrt-intercept/no_std",
    "wrt-decoder/no_std",
    "alloc"
]
alloc = ["wrt-error/alloc", "wrt-format/alloc", "wrt-host/alloc", "wrt-types/alloc", "wrt-intercept/alloc", "wrt-decoder/alloc", "dep:alloc"]
kani = ["wrt-host/kani", "wrt-intercept/kani"]

# Component Model features
component-model-core = ["wrt-format/component-model-core"]
component-model-values = ["wrt-format/component-model-values"]
component-model-resources = ["wrt-format/component-model-resources"]
component-model-async = ["wrt-types/component-model-async", "futures"]
component-model-error-context = ["wrt-types/component-model-error-context"]
component-model-threading = ["wrt-types/component-model-threading"]
component-model-all = [
    "component-model-core",
    "component-model-values",
    "component-model-resources",
    "component-model-async",
    "component-model-error-context",
    "component-model-threading"
]

[[example]]
name = "component_info_simple"
path = "examples/component_info_simple.rs"
required-features = ["std"]

[[example]]
name = "component_graph_view"
path = "examples/component_graph_view.rs"
required-features = ["std"]

[[example]]
name = "interceptor_example"
path = "examples/interceptor_example.rs"
required-features = ["std"]

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(test)'] }
unused_imports = "allow"
unused_variables = "allow"
unused_mut = "allow"
unused_macros = "allow" 
