[package]
name = "wrt-format"
version = "0.2.0"
edition = "2021"
description = "WebAssembly format handling for WRT"
license = "MIT"
repository = "https://github.com/avrabe/wrt"

[dependencies]
wrt-error = { path = "../wrt-error", version = "0.2.0" }
wrt-types = { path = "../wrt-types", version = "0.2.0" }

[dev-dependencies]
# For property testing
proptest = "1.0.0"

# For formal verification (moved to dependencies with optional flag)
[dependencies.kani-verifier]
version = "0.61.0"
optional = true

[features]
default = ["std", "component-model-core"]
std = ["wrt-types/std"]
no_std = ["wrt-types/no_std"]
optimize = ["wrt-types/optimize"]
safety = ["wrt-types/safety"]
# The 'kani' feature enables formal verification with the Kani verifier
kani = ["dep:kani-verifier", "wrt-types/kani"] 

# Component Model features
component-model-core = []  # Basic component model support
component-model-values = []  # 🪙 Experimental values
component-model-resources = []  # 🪙 Experimental resource types

# Grouped features
component-model-all = [
    "component-model-core",
    "component-model-values",
    "component-model-resources"
]

# Configuration for Kani verification
[package.metadata.kani]
default-unwind = 2