[package]
name = "wrt-format"
version = "0.2.0"
edition = "2021"
description = "WebAssembly format handling for WRT"
license = "MIT"
repository = "https://github.com/avrabe/wrt"

[dependencies]
wrt-error = { path = "../wrt-error", version = "0.2.0" }
wrt-types = { path = "../wrt-types", version = "0.2.0" }

[dev-dependencies]
# For property testing
proptest = "1.0.0"

# For formal verification (moved to dependencies with optional flag)
[dependencies.kani-verifier]
version = "0.61.0"
optional = true

[features]
default = [
    "std",
    "component-model-core",
    "component-model-values",
    "component-model-fixed-lists",
    "component-model-namespaces"
]
std = ["wrt-error/std", "wrt-types/std"]
no_std = ["wrt-error/no_std", "wrt-types/no_std"]
alloc = ["wrt-error/alloc", "wrt-types/alloc"]
optimize = ["wrt-types/optimize"]
safety = ["wrt-types/safety"]
# The 'kani' feature enables formal verification with the Kani verifier
kani = ["dep:kani-verifier"]

# Component Model features
component-model-core = ["wrt-types/component-model-core"]
component-model-values = ["wrt-types/component-model-values"]
component-model-resources = ["wrt-types/component-model-resources"]
component-model-canonical = []
component-model-fixed-lists = ["wrt-types/component-model-fixed-lists"]
component-model-error-context = ["wrt-types/component-model-error-context"]
component-model-async = ["wrt-types/component-model-async"]
component-model-threading = ["wrt-types/component-model-threading"]
component-model-namespaces = ["wrt-types/component-model-namespaces"]

# Grouped features
component-model-all = [
    "component-model-core",
    "component-model-values",
    "component-model-resources",
    "component-model-canonical",
    "component-model-fixed-lists",
    "component-model-error-context",
    "component-model-async",
    "component-model-threading",
    "component-model-namespaces"
]

# Config for linting
[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(test)', 'cfg(kani)', 'cfg(coverage)', 'cfg(doc)'] }

# Configuration for Kani verification
[package.metadata.kani]
default-unwind = 2