[package]
name = "wrt-verification-tool"
version.workspace = true
edition.workspace = true
description = "Verification tools for WebAssembly Runtime (WRT)"
license = "MIT"
repository = "https://github.com/avrabe/wrt"

[dependencies]
wrt-decoder = { path = "../wrt-decoder", version = "0.2.0" }
wrt-test-registry = { path = "../wrt-test-registry", version = "0.2.0" }
# For alloc support in no_std
alloc = { version = "1.0.0", optional = true, package = "rustc-std-workspace-alloc" }
# Feature-gated std dependencies
log = { version = "0.4", optional = true }

[features]
default = ["std"]
std = ["wrt-decoder/std", "log", "wrt-test-registry/std"]
no_std = ["wrt-decoder/no_std", "alloc", "wrt-decoder/alloc", "wrt-test-registry/no_std"]
alloc = ["dep:alloc", "wrt-decoder/alloc", "wrt-test-registry/alloc"]

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(test)'] } 