[package]
name = "wrt-instructions"
version = "0.2.0"
edition = "2021"
description = "WebAssembly instruction implementations for the WRT runtime"
license = "MIT OR Apache-2.0"
repository = "https://github.com/avrabe/wrt"

[features]
default = ["std"]
std = [
    "wrt-error/std", 
    "wrt-types/std",
    "wrt-runtime/std",
]
no_std = [
    "wrt-error/no_std", 
    "wrt-types/no_std",
    "wrt-runtime/no_std",
]
optimize = []  # Optional feature to bypass some safety checks in performance-critical paths
safety = []    # Additional safety features for ASIL-B compliance

[dependencies]
wrt-error = { path = "../wrt-error", version = "0.2.0" }
wrt-types = { path = "../wrt-types", version = "0.2.0" }
wrt-runtime = { path = "../wrt-runtime", version = "0.2.0" }

# No-std support
alloc = { version = "1.0.0", optional = true, package = "rustc-std-workspace-alloc" }

[dev-dependencies]
proptest = "1.4.0"

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(test)'] }
unsafe_code = "warn"
missing_docs = "warn" 