[package]
name = "wrt-types"
version = "0.1.0"
edition = "2021"
description = "Type definitions for WebAssembly Runtime (WRT)"
license = "MIT OR Apache-2.0"
repository = "https://github.com/avrabe/wrt"

[features]
default = ["std", "allocator_api", "log"]
std = ["wrt-error/std", "wrt-common/std", "log"]
allocator_api = []
alloc = ["dep:alloc"]
no_std = ["wrt-error/no_std", "wrt-common/no_std"]
optimize = []  # Optional feature to bypass some safety checks in performance-critical paths
safety = []    # Additional safety features for ASIL-B compliance
kani = ["dep:kani-verifier", "wrt-common/kani"]  # Feature for formal verification

[dependencies]
wrt-error = { path = "../wrt-error", version = "0.1.0" }
wrt-common = { path = "../wrt-common", version = "0.1.0" }

# For formal verification
kani-verifier = { version = "0.61.0", optional = true }

# No-std support
alloc = { version = "1.0.0", optional = true, package = "rustc-std-workspace-alloc" }

log = { version = "0.4", optional = true }

[dev-dependencies]
proptest = "1.4.0"
criterion = { version = "0.5", features = ["html_reports"] }

[package.metadata.kani]
default-unwind = 2

[lints.rust]
unsafe_code = "warn"
missing_docs = "warn"

[[bench]]
name = "safe_memory_benchmarks"
harness = false 